export const yearOptions = ['2018','2019','2020','2021'];
export const programs = ['Architecture', 'Planning', 'Design', 'TownPlanning', 'EngineeringandTechnology', 'Management', 'MCA', 'Pharmacy', 'Hotel ManagementandCatering'];
export const instituteTypes = ["Central University","Deemed University(Government)","Deemed University(Private)","Government","Govt aided","Private-Aided","Private-Self Financing","State Government University","Unaided - Private","University Managed","University Managed-Govt","University Managed-Private"];
export const statesOptions = [ 
    "Andaman & Nicobar Islands",
    "Andhra Pradesh",
    "Arunanchal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadara & Nagar Haveli",
    "Daman and Diu",  
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu & Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ]